### ISSUE TITLE
proxy doesnt work on telegram desktop (windows) and telegram x (android) and telegram ios

### ISSUE THREAD

**Issue by ea1234567** [alexbers/mtprotoproxy#83] opened 2019-04-17 22:35 UTC
Proxy was ok until today
but today proxy only works on telegram android
plz update codes 

telegram android= ok
telegram x android = error
telegram desktop windows = error
telegram ios = error

Im using latest version on windows server.everything was ok.i didnt have any problem on clients and platforms

**Comment by d0tfile** [comment] 2019-04-18 09:39
I have mtprotoproxy on Gentoo, never had an issue.

**Comment by alexbers** [comment] 2019-04-18 11:11
it is likely because of clock time skew on your server. Please check that your system clock is precise because the time is very important for the protocol.

**Comment by ParaNULL** [comment] 2019-04-19 08:21
I've got the same problem... Will follow the developer suggestion and Will report it back

**Comment by ParaNULL** [comment] 2019-04-19 08:57
Just yum installed the ntp and configured the time zone to my local time "timedatectl set-timezone " and now using date command it shows the correct time and date but the problem still exists...the strange problem is the script is working on one of my servers and telegram x but it's not working on my other servers.

**Comment by ParaNULL** [comment] 2019-04-19 09:22
Checked the main script and they've got the same problem so it should be more than a time problem
https://github.com/TelegramMessenger/MTProxy/issues/293

**Comment by alexbers** [comment] 2019-04-19 10:10
hm, interesting. Will check against those versions. May be the telegram authors had broken something in some update.

**Comment by ea1234567** [comment] 2019-04-19 10:28
@ParaNULL  @alexbers 

i think this is new censorship method
i changed my server ip and problem solved
im from iran

**Comment by ea1234567** [comment] 2019-04-19 10:30
and when i turned on vpn my problem solved

**Comment by ParaNULL** [comment] 2019-04-19 10:49
I'm From the same country ...are you a beta tester of telegram?! After the last update on 17 app the problem appeared...maybe another censorship method but why it's not working on other client's and I can still ssh to my server... I've experienced the server IP blocked and censorship but this time it's 100% related to telegram x

**Comment by ea1234567** [comment] 2019-04-19 11:23
@ParaNULL 
Yes im beta tester but telegram desktop had problem too and telegram ios
only telegram android was ok
im sure that its censorship because when i turend on vpn problem solved

**Comment by samanmohamadi** [comment] 2019-04-19 18:56
same problem here,  my proxy doesn't work on the desktop any more :(

**Comment by ea1234567** [comment] 2019-04-19 19:14
@samanmohamadi 
Change your ip

**Comment by alexbers** [comment] 2019-04-19 23:49
I've just implemented active fingerprinting detection/protection in https://github.com/alexbers/mtprotoproxy/commit/4cae6290b9529485125366771005460309a835b5. They may use a sophisticated replay attack for proxy fingerprinting and blocking. This commit detects such attacks and blocks them.

Please test it, if all is ok, it will go to the stable branch.

**Comment by erfantkerfan** [comment] 2019-04-20 07:20
I'm from Iran too
the above commit solved the problem
(If you IP haven't been blocked ofcourse)
please commit [this ](https://github.com/alexbers/mtprotoproxy/commit/4cae6290b9529485125366771005460309a835b5) to stable branch.

**Comment by alexbers** [comment] 2019-04-20 10:04
Implemented one more protection against replay-based proxy fingerprinting: https://github.com/alexbers/mtprotoproxy/commit/f55ae68092b4f07e247baa18ad35b014380a9eeb.

Don't sure if is will work with every possible client, will test for little bit.

**Comment by ea1234567** [comment] 2019-04-20 10:47
@alexbers  Thanks. I will test that too
but why when i turned on vpn all clients was ok
and when turned vpn off just telegram android was ok

**Comment by ParaNULL** [comment] 2019-04-20 13:45
@alexbers tested the replay based proxy finger printing method and it's working great despite it doesn't show the ping after connection stablishment

**Comment by sohrabafard** [comment] 2019-04-20 19:42
Not working on Iphone SE!

**Comment by alexbers** [comment] 2019-04-20 20:42
Which version of client you have installed on iphone se?

**Comment by sohrabafard** [comment] 2019-04-21 14:36
Last version from app store

**Comment by m8603164** [comment] 2019-04-23 09:43
Hello
Unfortunately, even with the new config, again the problem has returned from this morning!
The proxy server is not connected to the telegram X and the desktop telegram.

**Comment by alexbers** [comment] 2019-04-23 10:05
Hello, are the messages for active fingerprinting appear when you connecting?

**Comment by m8603164** [comment] 2019-04-23 10:13
> Hello, are the messages for active fingerprinting appear when you connecting?

With by new config, last night I was able to connect easily on the telegram X. But this morning it was again like before! The same problem is with each new server with the new IP! And it only works on the conventional telegram, but not on the telegram X! :(
Of course, I did not understand you from viewing the fingerprint message and I did not see any message in this regard.

**Comment by m8603164** [comment] 2019-04-24 17:35
Friends please guide me, there is no way?

**Comment by erfantkerfan** [comment] 2019-04-25 08:34
> Friends please guide me, there is no way?

use the stable branch for now.
there is still the problem with ping and desktop+IOS not beeing able to connect to the master branch.

**Comment by m8603164** [comment] 2019-04-26 19:47
> use the stable branch for now.
> there is still the problem with ping and desktop+IOS not beeing able to connect to the master branch.

What do you mean by a stable branch?
Please refer to the link.
I still see proxies in telegram X, connecting them without any problems! Which config they use ?!
Thank you

**Comment by ea1234567** [comment] 2019-05-04 06:24
my new proxy is ok with all of clinets except telegram ios
telegram desktop is ok

**Comment by erfantkerfan** [comment] 2019-05-04 20:10
latest commit solved the problem for desktop clients but IOS devices still can not connect with fingerprint

**Comment by uprt** [comment] 2019-05-04 20:21
I can confirm that proxy from master branch works with Android client, but I can't connect to it using iOS version. Looks like there are some differences in client implementation.
Please feel free to contact me if you need additional logs or debug info.

**Comment by alexbers** [comment] 2019-05-08 22:04
It is interesting, because I am using iOS version for quite a lot of time. What version of iOS telegram client are you using?

**Comment by ea1234567** [comment] 2019-05-08 22:08
@alexbers Im using latest version

**Comment by alexbers** [comment] 2019-05-08 22:10
I am also using the latest version and everything is ok. Could you please share the proxy link to @bay3255

**Comment by alexbers** [comment] 2019-05-08 22:38
I've understand why it doesn't work and committed a temporary fix: https://github.com/alexbers/mtprotoproxy/commit/af8c102449e26512ee1da7732f8047eeba9f0089. Now it should work

**Comment by ea1234567** [comment] 2019-05-09 06:38
Problem Solved
Tnx
Closed

**Closed** 2019-05-09 06:39 UTC
