### ISSUE TITLE
Slow Connecting...

### ISSUE THREAD

**Issue by Neo-vortex** [alexbers/mtprotoproxy#50] opened 2018-08-04 10:35 UTC
I have the server running on a dual core and 4 GO RAM, but the problem is the time that it takes to connect to the proxy is too much, sometimes the ping is 3xxx ms. but after connecting, the speed is charming.
I have even tried to set
`FAST_MODE = True`  
But no luck, the server is super fast at ping running other MTproto server implementations.
Anyone with the same problem or a tip?

**Comment by devbreath** [comment] 2018-08-04 14:36
Small workaround, you can set CLIENT_KEEPALIVE = 60*60 in config.py.
It will increase memory use and  not help with initial connect, but should increase speed of connection after.

**Comment by alexbers** [comment] 2018-08-04 16:41
Could you try to ping several telegram servers from your host and post the ping times. The list of telegram servers can be found on https://core.telegram.org/getProxyConfig

**Comment by Neo-vortex** [comment] 2018-08-04 16:48
some ping Results:
Reply from 149.154.175.50: bytes=32 time=103ms TTL=54

**Comment by Neo-vortex** [comment] 2018-08-04 17:05
some ping results : 

**Reply from 91.108.4.219: bytes=32 time=10ms TTL=56
Reply from 149.154.175.50: bytes=32 time=103ms TTL=54
Reply from 149.154.165.109: bytes=32 time=10ms TTL=55
Reply from 91.108.56.181: bytes=32 time=173ms TTL=52**

**Comment by alexbers** [comment] 2018-08-04 17:25
it seems the ping times are ok. The additional delay should be about 0.01-0.2 sec. May be the problem is in the ping time between the client and the proxy? Also you can increase the buffer sizes by writing TO_CLT_BUFSIZE = 163840 and TO_TG_BUFSIZE = 655360 to config.py. It should became faster at cost of memory

**Comment by Neo-vortex** [comment] 2018-08-04 20:26
wow  `TO_TG_BUFSIZE = 655360 ` did the job
now the ping is about 120 130 ms, very well, thanks :)

**Comment by alexbers** [comment] 2018-08-25 18:56
could you, please, send the proxy log and the data about cpu load

**Comment by alexbers** [comment] 2020-01-02 21:12
this should be fixed in the latest version

**Closed by alexbers** 2020-01-02 21:12 UTC
