### ISSUE TITLE
Error "Fatal read error on pipe transport"

### ISSUE THREAD

**Issue by 123asd321dsa** [alexbers/mtprotoproxy#42] opened 2018-07-13 07:29 UTC
Fatal read error on pipe transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0x03B24410>
transport: <_ProactorSocketTransport closing fd=536>
Traceback (most recent call last):
  File "C:\Users\-----\AppData\Local\Programs\Python\Python37-32\lib\asyncio\proactor_events.py", line 255, in _loop_reading
    data = fut.result()
  File "C:\Users\-----\AppData\Local\Programs\Python\Python37-32\lib\asyncio\windows_events.py", line 732, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\-----\AppData\Local\Programs\Python\Python37-32\lib\asyncio\windows_events.py", line 428, in finish_recv
    return ov.getresult()
OSError: [WinError 121] The semaphore timeout period has expired

**Comment by alexbers** [comment] 2018-07-13 07:59
It seems that exception is a duplicate of https://github.com/alexbers/mtprotoproxy/issues/40. It should be fixed in the master version and now it is merged to the stable branch also. Could you retry with the latest version.

**Closed by alexbers** 2018-07-13 07:59 UTC
